name: tests-boa

on: [push]

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HYPOTHESIS_PROFILE: no-shrink

jobs:
  tests:
    needs: pre-commit
    name: ${{ matrix.folder }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: "tests/unitary"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          - folder: "tests/e2e"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          # - folder: "tests/stateful" not ready yet
          #   runs-on: "blacksmith-32vcpu-ubuntu-2204"
          # Old tests to be migrated
          - folder: "tests/flashloan"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          - folder: "tests/controller"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          - folder: "tests/price_oracles"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          - folder: "tests/zaps"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          - folder: "tests/amm"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          - folder: "tests/lending"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
          - folder: "tests/stableborrow --ignore=tests/stableborrow/stabilize"
            runs-on: "blacksmith-32vcpu-ubuntu-2204"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6.7
        with:
          enable-cache: true  # Enables built-in caching for uv

      - name: Cache Compiler Installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.vvm
          key: compiler-cache-${{ hashFiles('**/uv.lock') }}

      - name: Set up Python 3.12.6
        run: uv python install 3.12.6

      - name: Install Requirements
        run: uv sync

      - name: Run tests
        run: |
          uv run pytest ${{ matrix.folder }} -n auto
